jenkins-infra/digitalocean

Jenkinsfile_k8s
versions.tf

as per https://github.com/jenkins-infra/shared-tools/issues/8
use of the terraform 1.2.x within the hashicorp docker image

chore: add the hashicorp-tools image as updatecli parameter to use terraform version 1.1.x

---

updatecli/updatecli.d/hashicorp.yml

as per https://github.com/jenkins-infra/aws/issues/120
keep track of the hashicorp tools image version

chore: keep track of hashicorp-version with updatecli

---

updatecli/scripts/terraform-get-upgraded-lockfile.sh

If the script fails it means updatecli has to be executed in the same environment as the rest of the pipeline to get the "current" terraform
Follow-up of https://github.com/jenkins-infra/digitalocean/pull/13

fix: only test the presence of terraform in updatecli script

---

.gitignore
autoscaled-node-pool.tf
doks-cluster.tf
locals.tf
variables.tf

`doctl kubernetes options versions` doesn't return anything for 1.20.x any more.
Ref: https://github.com/jenkins-infra/helpdesk/issues/2861

fix: hardcode k8s version until the switch to 1.21

---

Jenkinsfile_k8s

While checking for https://github.com/jenkins-infra/helpdesk/issues/2861 to be closed, it appearead that this repository is not executed daily.

chore(pipeline) Execute the pipeline every days

---

Jenkinsfile_k8s

Related to https://github.com/jenkins-infra/helpdesk/issues/2884.
- GitHub checks have been disabled on infra.ci - https://github.com/jenkins-infra/kubernetes-management/pull/2245
- Credentials rotated (private: https://github.com/jenkins-infra/charts-secrets/commit/3701045ae7e21df2a37ebd0c570e4315b4200f74)
This PR enables the terraform job again: it should create a brand new cluster once merged.

Enable digitalocean job again

---

autoscaled-node-pool.tf

As per https://github.com/jenkins-infra/helpdesk/issues/2917, this change request disables the autoscaled node pool.
The goal is to keep the cluster running, but without any beefy machine, until we can be sure if we continue using digital ocean or if we stop it.

feat: disable the autoscaled-node-pool

---

variables.tf

as per : https://github.com/jenkins-infra/helpdesk/issues/2930
upgrade kubernetes from 1.21 to 1.22 
```
Changes to Outputs:
~ dok8s-versions = [
- "1.21.11-do.1",
+ "1.22.8-do.1",
]
You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.
```

kubernetes upgrade from 1.21 to 1.22

---

doks-public-cluster.tf
load-balancer.tf
locals.tf

To be used for public services like the Artifact Caching Proxy, in order to avoid putting credentials on the cluster dedicated to ci.jenkins.io agents.
Fixes #66
Ref: https://github.com/jenkins-infra/helpdesk/issues/3114

feat: public cluster

---

doks-public-cluster.tf
locals.tf

As the artifact-caching-proxy requests 2 vCPU and 4Go of memory, it couldn't be deployed on doks-public cluster as it hasn't enough resources per node:
> pod didn't trigger scale-up: 1 Insufficient cpu, 1 Insufficient memory
Ref: https://github.com/jenkins-infra/helpdesk/issues/2752

fix: increase small node pool size to accommodate artifact-caching-proxy resources requests

---

doks-cluster.tf
doks-public-cluster.tf

Ref: https://github.com/jenkins-infra/helpdesk/issues/3387

chore: update `doks` and `doks-public` clusters to Kubernetes 1.24

---

doks-cluster.tf

Depends on https://github.com/jenkins-infra/digitalocean/pull/102
This PR is related to https://github.com/jenkins-infra/helpdesk/issues/3391.
It increases the maximum capacity of the `doks` cluster to 50 nodes (to allow up to 150 pod agents)

feat(doks) increase node pool capacity to 50 max 

---

doks-public-cluster.tf

Follows up #102 
- Setting up the maximum 4 nodes (upper limit). Twice the nominal limit (2 nodes).
- Maintenance window was at `04:00am` UTC for both clusters. Switched this cluster (`doks-public`) to `06:00am` UTC (2 hours later) to avoid an upgrade of the 2 clusters at the same time

feat(doks-public) limit autoscaled nodepool to max. 4 nodes + define maintenance window 2 hours later

---

doks-cluster.tf

As the droplets limit on DigitalOcean account has been increased to 100, we can now increase this cluster capacity to be the same as the AWS one.
Ref: https://github.com/jenkins-infra/jenkins-infra/pull/2679 & https://github.com/jenkins-infra/kubernetes-management/pull/3661

feat(doks): increase node pool max nodes to 50

---

.terraform.lock.hcl
doks-cluster.tf
doks-public-cluster.tf

- HA upgrade done through the UI because https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/kubernetes_cluster#ha specifies that the cluster would deleted and re-created if done through Terraform
- Job is disabled on infra.ci
- A local terraform plan states: 
```
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
~ resource "digitalocean_kubernetes_cluster" "doks_cluster" {
~ ha             = false -> true
id             = "8f6e486f-86e9-45d0-a52b-d5554c70f4ec"
name           = "jenkins-infra-doks-hkuxfyvb"
tags           = [
"managed-by:terraform",
]
~ updated_at     = "2023-06-21 13:24:07 +0000 UTC" -> "2023-06-22 15:22:50 +0000 UTC"
}
~ resource …
```

feat(doks,doks-public) enable HA for Kubernetes control-planes

---

updatecli/updatecli.d/terraform-providers.yaml

This PR aligns manifest syntax with other manifests like https://github.com/jenkins-infra/digitalocean/blob/main/updatecli/updatecli.d/hashicorp-tools.yml or (more exactly) https://github.com/jenkins-infra/azure/blob/main/updatecli/updatecli.d/terraform-providers.yaml
Note: no `title` in the `action` section is needed here as there is no variable in it, thus the `name` will be used as PR title.
Follow-up of https://github.com/jenkins-infra/digitalocean/pull/122#discussion_r1239756668

fix(updatecli): replace `title` by `name` in terraform-providers

---

.terraform.lock.hcl
doks-cluster.tf
doks-public-cluster.tf

Build on the principal branch fails since 2 days with the following kind of errors:
```
Error: Get "http://localhost/api/v1/namespaces/kube-system/serviceaccounts/infraciadmin": dial tcp [::1]:80: connect: connection refused
```
When DigitalOcean upgrades our clusters for minor versions, the kube-config changes, which lead to errors during plan and refresh: there is a dead-lock for terraform with the data sources used to configure kubernetes provider in modules.
Found in https://github.com/hashicorp/terraform-provider-kubernetes/issues/1635#issuecomment-1068468254

chore(doks,doks_public) ignore cluster version changes in the lifecycle

---

archives.jenkins.io.tf

Attempt to fix https://github.com/jenkins-infra/digitalocean/pull/157#issuecomment-1733925319

hotfix(archives.jenkins.io) correct volume name to only use lowercase alphanum

---

archives.jenkins.io.tf

Found thanks to https://developer.hashicorp.com/terraform/tutorials/applications/digitalocean-provider

hotfix(archives.jenkins.io) user_data is not base64 encoded

---

archives.jenkins.io.tf
dns.tf
doks-public-cluster.tf

As suggested by @lemeurherve , let's manage the DNS records of services hosted in DO through a DNS child zone.
Related to https://github.com/jenkins-infra/helpdesk/issues/3760
This PR is the first step: it creates the DNS child zone with records for:
- `archives.do` 
- Both IPv4 (`A` record) and IPv6 (`AAAA` record)
- Rename the newly created VM from `do.archives.jenkins.io` to `archives.do.jenkins.io` to follow DNS records => re-create the VM but no problem it is still being evaluated
- `repo.do`
- Added a data source to retrieve the LB's IPv4 (no IPv6), ss the LB must be managed by the `doks-public` cluster, and only by it
- Updated the `doks-public` output to use the LB data source (and avoid having an empty IP)
- Ipv4 only (`A` record).
⚠️ This won't change the current DNS records …

feat: manage DigitalOcean service DNS records

---

archives.jenkins.io.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/3760
This PR adds the following changes:
- Grow the volume to 750 Gb
- Verify we can grow volume easily without requiring LVS or fancy tasks
- I forgot to count in 1024 base, so the real avilable space (once formatted and mounted) is 660G for a 700G volume, which means 78% of usage (a bit short innit?)
- Allow the current Oracle VM hosting archives.jenkins.io to connect with SSH to this new VM, for data migration

feat(archives.jenkins.io) prepare data migration from Oracle

---

archives.jenkins.io.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/3760
This outbount rsync is required by https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/archives/mirrorsync.erb

feat(archives) allow outbound rsync to OSUOSL and updates.j - 

---

archives.jenkins.io.tf
main.tf

This PR is a first try at sharing a set common values across our terraform projects.
A new [data-only Terraform module](https://developer.hashicorp.com/terraform/language/modules/develop/composition#data-only-modules) has been added in the jenkins-infra/shared-tools to hold the shared values: https://github.com/jenkins-infra/shared-tools/commit/36589078701232007dbdf8b5034fd93901d072c3.
The following changes are introduced to the archives.jenkins.io VM:
- Use "IP" instead of CIDR mask for firewall rules
- Add outbound SSH to allow rsync through SSH protocol (instead of rsync) to OSUOSL or pkg VM
- Restrict rsync to only OSUOSL or pkg VM
💡 Notes:
- This module, for now, only specify a set of outputs providing the shared data to projects. It may provide data sources (Azure DNS zones or …

chore: reuse shared data from the new 'jenkins-infra' common module

---

doks-cluster.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/3683

feat(doks) bump Kubernetes version from 1.25.to 1.26

---

doks-public-cluster.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/3683
Self-merging with a manually applied upgrade

feat(doks-public) bump Kubernetes version from 1.25.to 1.26

---

Jenkinsfile_k8s
versions.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/3823

chore: use terraform `1.6` instead of `1.1`

---

doks-public-cluster.tf

as per https://github.com/jenkins-infra/helpdesk/issues/3948 waiting for https://github.com/jenkins-infra/kubernetes-management/pull/4982
EDIT: include a removal of the trick https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/kubernetes_cluster#kubernetes-terraform-provider-example not needed anymore with the terraform upgrade.

feat(doks-public) bump Kubernetes version from 1.26.to 1.27 digitalocean

---

doks-cluster.tf
doks-public-cluster.tf

This PR comes from the initial work on https://github.com/jenkins-infra/helpdesk/issues/3948 (see PRs #179 #180 and #182 ).
It introduces the following changes:
- chore: Bump shared tools to latest version
- Cherry pick changes by @smerle33 in #179 to remove the data source used to configure the 2 instances of the kubernetes terraform provider used to create resources in the cluster `doks` and `doks-public`
- This change is possible as we are using Terraform 1.6 which solved the lifecycle problems we had with DigitalOcean provider and the 1.1.x version of Terraform
- chore: silence warnings related to `lifecycle` which is not required anymore
=> As #179 and #180 showed, and since our clusters are now up to date with 1.26.x line, this PR should NOT introducer any change to the DigitalOcean …

chore(`doks` / `doks public`) remove datasource kube hacks around lifecycle

---

doks-cluster.tf

Fixup of #183
Same expectations: we forgot to apply the change to `doks` itself.
Same expectation: no changes should be done in the plan.

chore(doks) remove data source hack used to setup kubernetes provider

---

doks-public-cluster.tf

as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1948211120
```
Terraform will perform the following actions:
~ resource "digitalocean_kubernetes_cluster" "doks_public_cluster" {
id                               = "<redacted>"
name                             = "jenkins-infra-doks-public-hkuxfyvb"
tags                             = [
"managed-by:terraform",
]
~ version                          = "1.26.13-do.0" -> "1.27.10-do.0"
}
Plan: 0 to add, 1 to change, 0 to destroy.
```

feat(doks-public) bump Kubernetes version from 1.26.to 1.27 digitalocean (second round)

---

archives.jenkins.io.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/4330
Applied manually already

feat(archives.jenkins.io) upsize archives.jenkins.io to ensure good performances when fall-backing in

---

archives.jenkins.io-cloudinit.tftpl
archives.jenkins.io.tf

This PR updates the cloudinit.
Please note: in DigitalOcean, the default Administrator user is `root`. As such, we pass the empty string to avoid trying to change `root` ID 😅

fix(archives.jio) correct cloudinit call

---

archives.jenkins.io.tf
firewalls.tf

as per https://github.com/jenkins-infra/helpdesk/issues/4621
we need to separate the firewalls and to split them in order to use them for multiple droplets

chore(archives.jio): split firewall in 2 subsets

---

puppet.do.jenkins.io.tf

for https://github.com/jenkins-infra/helpdesk/issues/4621 and as per https://github.com/jenkins-infra/digitalocean/pull/223#issuecomment-2776383824
renaming the puppet machine to avoid `_`

fix(puppet): rename machine name to comply DO rules

---

firewalls.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4653

feat(archives) allow inbound rsync from everywhere

---

.terraform.lock.hcl
Jenkinsfile_k8s
outputs.tf
versions.tf

We expect the report in https://reports.jenkins.io/jenkins-infra-data-reports/digitalocean.json

chore: export report and cleanup provider setup
