- Jenkinsfile_k8s
- Makefile
- backend-config
- locals.tf
- tests/terraform_main_test.go
- variables.tf
- versions.tf
> fix: terraform fmt -recursive & remove backend-config from repo

- README.adoc
> chore: fix links

- Jenkinsfile_k8s
- updatecli/updatecli.d/hashicorp-tools.yml
> chore: bump hashicorp image version and fix updatecli

- .terraform.lock.hcl
- doks-cluster.tf
- locals.tf
- variables.tf
> Fixup upgrade to kubernetes 1.21 as per helpdesk #2866

- autoscaled-node-pool.tf
Reverts jenkins-infra/digitalocean#35 as we've been given additional credits by DigitalOcean
Ref: https://github.com/jenkins-infra/helpdesk/issues/2917
> Revert "feat: disable the autoscaled-node-pool"

- doks-cluster.tf
as per https://github.com/jenkins-infra/helpdesk/issues/2930
> fix(doks_cluster): remove version from lifecycle exception

- data.tf
- doks-cluster.tf
- doks-public-cluster.tf
- locals.tf
- variables.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3053
> feat(doks-public): upgrade kubernetes to 1.23

- doks-cluster.tf
upgrade the second kubernetes cluster within digital ocean to kubernetes 1.23
> feat(doks): upgrade to kubernetes 1.23

- doks-public-cluster.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3582
> feat(doks) bump Kubernetes to 1.25.x

- doks-cluster.tf
as per jenkins-infra/helpdesk#3582
> feat(doks): upgrade to kubernetes 1.25

- doks-public-cluster.tf
Follow-up of https://github.com/jenkins-infra/azure-net/pull/134/
> chore(doks-public): output public IPv4 address of the cluster

- archives.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3760
> feat(archives.jenkins.io) allow outbound connection to our puppet master

- doks-public-cluster.tf
Reverts jenkins-infra/digitalocean#179
upgrade failed
> Revert "feat(doks-public) bump Kubernetes version from 1.26.to 1.27 digitalocean"

- doks-cluster.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1938993039
> feat(doks): upgrade kubernetes from 1.26 to 1.27

- archives.jenkins.io.tf
- firewalls.tf
- locals.tf
setting dynamics tags (not the usage of digitalocean for firewalls but as indications for us)
> chore(tags): setting defaults tags as string

- firewalls.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
Twin of https://github.com/jenkins-infra/aws/pull/565/files
> feat(firewalls) add new IPs to allow management from new sponsorship clusters

- firewalls.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2839488075
> cleanup: migrate settings from privatek8s to privatek8s-sponsorship cluster

- outputs.tf
This PR is to retrieve the droplet IP
cc @dduportal
> chore(outputs.tf): retrieve IP address of jay.training

- firewalls.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4690
> feat(firewalls) update infra.ci outbound IPs (both cluster and agents subnets)

- usage.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/1626
lets increase the volume size to 1500Go
> feat(usage): extend volume
